import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Poppins,
  Inter,
  Montserrat,
} from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const montserrat = Montserrat({
  variable: "--font-Montserrat",
  subsets: ["latin"],
  weight: ["400", "700"],
});
const poppins = Poppins({
  variable: "--font-Poppins",
  subsets: ["latin"],
  weight: ["400", "700"],
});
const inter = Inter({
  variable: "--font-Inter",
  subsets: ["latin"],
  weight: ["400", "700"],
});
const integralcf = localFont({
  src: "./fonts/IntegarCFbold.otf",
  variable: "--font-integral-cf",
  weight: "100 900",
});
const satoshi = localFont({
  src: "./fonts/Satoshi-Medium.otf",
  variable: "--font-satoshi-medium",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Hunain's Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${poppins.variable} ${satoshi.variable} ${integralcf.variable} ${montserrat.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
